"""Product popup with mocked chrome.runtime/storage in Chromium; NOT an extension/DNR test.
Run: python extension/tests/ui/popup_ui.py (requires Python playwright + Chromium).
"""
from pathlib import Path
import http.server, threading, functools, json, shutil
from playwright.sync_api import sync_playwright, expect
root=Path(__file__).resolve().parents[2]
evidence=root.parent/'docs/implementation/evidence/popup-ui'
evidence.mkdir(parents=True,exist_ok=True)
class Quiet(http.server.SimpleHTTPRequestHandler):
    def log_message(self,*args): pass
server=http.server.ThreadingHTTPServer(('127.0.0.1',0),functools.partial(Quiet,directory=str(root)))
threading.Thread(target=server.serve_forever,daemon=True).start()
mock=r'''window.mock={state:null,fail:false,gate:null,calls:[],auth:{phase:'UNREGISTERED',guest_start_allowed:true,server_url:'http://127.0.0.1:8080/api/v1',web_origin:'http://127.0.0.1:5173',callback_uri:'chrome-extension://test/popup/popup.html'},items:[{site_id:'s1',version:1,canonical_host:'naver.com',display_name:'네이버',purpose:'DISTRACTION',access_policy:'BLOCK',include_subdomains:true}]};window.chrome={storage:{local:{get:async()=>({focurve_ui_theme:'dark'}),set:async data=>{window.savedTheme=data.focurve_ui_theme}}},runtime:{sendMessage:async m=>{mock.calls.push(m);if(mock.failUpdate&&m.type==='DEV_GUEST_SITE_UPDATE')return {request_id:m.request_id,status:'ERROR',data:null,error:{code:'VERSION_CONFLICT'}};let data=null;if(m.type==='FOCURVE_AUTH_BEGIN')mock.auth={...mock.auth,phase:'LINK_PENDING',guest_start_allowed:false};if(m.type==='FOCURVE_AUTH_POLL'&&mock.approve)mock.auth={...mock.auth,phase:'LINKED',guest_start_allowed:false};if(m.type.startsWith('FOCURVE_AUTH_'))data=mock.auth;if(m.type.startsWith('MEMBER_DELIVERY_')){if(mock.deliveryStorageFail)return {request_id:m.request_id,status:'ERROR',data:null,error:{code:'DELIVERY_STORAGE_UNAVAILABLE'}};if(mock.deliveryFail)throw Error('OFFLINE');data=mock.delivery||{total:0,retry_after_at:0,next_retry_at:null,counts:{QUEUED:0,IN_FLIGHT:0,RESPONSE_UNCONFIRMED:0,PENDING_DEPENDENCY:0,AUTH_REQUIRED:0,REJECTED:0,ACKED:0,LOCAL_REVIEW_REQUIRED:0}};}if(m.type==='DEV_MEMBER_EXECUTION_STATE')data=mock.memberExecution||null;if(m.type==='DEV_MEMBER_EXECUTION_END'&&mock.memberExecution){mock.memberExecution={status:'RELEASED',session_id:'member-session'};data=mock.memberExecution;}if(mock.fail&&m.type==='DEV_SESSION_STATE')throw Error('OFFLINE');if(m.type==='DEV_GUEST_SITE_LIST')data={items:mock.items};if(m.type==='DEV_SESSION_STATE')data=mock.state;if(m.type==='DEV_SESSION_START'){await new Promise(resolve=>mock.gate=resolve);mock.state={session_id:'session1',status:'RUNNING',started_at:new Date().toISOString(),planned_end_at:new Date(Date.now()+1500000).toISOString(),snapshot:{sites:structuredClone(mock.items)}};data=mock.state;}if(m.type==='DEV_SESSION_END'){await new Promise(resolve=>mock.gate=resolve);mock.state={...mock.state,status:'ENDED',active_duration_ms:65000};data=mock.state;}if(m.type==='DEV_ACCESS_LIST')data=mock.access||{session_id:mock.state?.session_id,items:[],total_access:0,repeat_access:0};if(m.type==='DEV_GUEST_SITE_UPDATE'){const i=mock.items.findIndex(s=>s.site_id===m.payload.site_id);data={...mock.items[i],...m.payload.site,canonical_host:m.payload.site.url,version:mock.items[i].version+1};mock.items[i]=data;}if(m.type==='DEV_GUEST_SITE_DELETE'){data={site_id:m.payload.site_id,deleted_at:new Date().toISOString()};mock.items=mock.items.filter(s=>s.site_id!==m.payload.site_id);}if(m.type==='DEV_GUEST_SITE_CREATE'){data={...m.payload,canonical_host:m.payload.url,site_id:'s2',version:1};mock.items.push(data);}return {request_id:m.request_id,status:'OK',data,error:null};}}};'''
checks=[]
try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch(headless=True,executable_path=shutil.which("chromium"))
  page=browser.new_page(viewport={'width':400,'height':675},device_scale_factor=1)
  errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
  page.add_init_script(mock)
  page.goto(f'http://127.0.0.1:{server.server_port}/popup/popup.html')
  expect(page.locator('#start-focus')).to_be_enabled();expect(page.locator('#policy-summary')).to_contain_text('차단 1개');checks.append('initial verified state / dynamic policies')
  page.screenshot(path=str(evidence/'main-dark.png'),full_page=True)
  page.locator('#preferences').click();page.locator('#theme-mode').select_option('light');expect(page.locator('html')).to_have_attribute('data-theme','light');assert page.evaluate('savedTheme')=='light';page.locator('#preferences summary').click();page.screenshot(path=str(evidence/'main-light.png'),full_page=True);checks.append('theme selection and persistence request')
  page.locator('nav [data-page=sites]').click();expect(page.locator('#site-list')).to_contain_text('네이버');page.locator('#site-search').fill('missing');expect(page.locator('#site-list li')).to_be_hidden();page.locator('#site-search').fill('');checks.append('site navigation and search')
  page.locator('#site-list button').filter(has_text='수정').click();expect(page.locator('#site-url')).to_have_value('naver.com');page.locator('#cancel-edit').click();expect(page.locator('#site-editor')).to_be_hidden();checks.append('existing edit and cancel preserved')
  page.locator('#add-site').click();page.locator('#site-url').fill('example.com');page.locator('#site-name').fill('예시');page.locator('#save-site').click();expect(page.locator('#site-list')).to_contain_text('example.com');checks.append('registration uses existing adapter')
  page.screenshot(path=str(evidence/'sites-light.png'),full_page=True)
  page.locator('#site-list li').filter(has_text='example.com').get_by_role('button',name='수정',exact=True).click();page.locator('#site-name').fill('수정한 이름');page.screenshot(path=str(evidence/'edit-light.png'),full_page=True);page.locator('#save-site').click();expect(page.locator('#site-list')).to_contain_text('수정한 이름');assert page.evaluate("mock.calls.find(m=>m.type==='DEV_GUEST_SITE_UPDATE').payload.expected_version")==1;checks.append('edit forwards expected version')
  page.evaluate('mock.failUpdate=true');page.locator('#site-list li').filter(has_text='example.com').get_by_role('button',name='수정',exact=True).click();page.locator('#site-name').fill('충돌 후 보존');page.locator('#save-site').click();expect(page.locator('#site-result')).to_contain_text('다른 화면');expect(page.locator('#site-name')).to_have_value('충돌 후 보존');page.locator('#cancel-edit').click();page.evaluate('mock.failUpdate=false');checks.append('version conflict preserves unsaved input')
  row=page.locator('#site-list li').filter(has_text='example.com');row.get_by_role('button',name='삭제',exact=True).click();assert not page.evaluate("mock.calls.some(m=>m.type==='DEV_GUEST_SITE_DELETE')");row.get_by_role('button',name='삭제 확인',exact=True).click();expect(page.locator('#site-list')).not_to_contain_text('example.com');checks.append('delete requires confirmation')
  page.locator('#sites-page [data-page=focus]').click();page.locator('#start-focus').click();expect(page.locator('#focus-title')).not_to_have_text('집중 진행 중');expect(page.locator('#focus-countdown')).to_be_hidden();checks.append('pending apply never shows running')
  page.evaluate('mock.gate()');expect(page.locator('#focus-title')).to_have_text('집중 진행 중');expect(page.locator('#focus-countdown')).to_be_visible();page.screenshot(path=str(evidence/'running-light.png'),full_page=True)
  page.evaluate("mock.items.push({site_id:'later',canonical_host:'later.com',display_name:'다음 세션',purpose:'DISTRACTION',access_policy:'BLOCK'})");page.locator('#focus-page [data-page=sites]').click();page.locator('#reload-sites').click();expect(page.locator('#site-list')).to_contain_text('later.com');page.locator('#sites-page [data-page=focus]').click();expect(page.locator('#policy-summary')).to_contain_text('차단 1개');checks.append('running summary uses frozen snapshot')
  page.locator('#request-end').click();expect(page.locator('#end-dialog')).to_be_visible();page.locator('#continue-focus').click();expect(page.locator('#end-dialog')).not_to_be_visible();assert not page.evaluate("mock.calls.some(m=>m.type==='DEV_SESSION_END')");checks.append('cancel end sends no end request')
  page.locator('#request-end').click();page.locator('#end-focus').click();expect(page.locator('#result-page')).to_be_hidden();expect(page.locator('#focus-countdown')).to_be_hidden();checks.append('pending release never shows completed result')
  page.evaluate('mock.gate()');expect(page.locator('#result-page')).to_be_visible();expect(page.locator('#session-summary')).to_contain_text('1분 5초');expect(page.locator('#recent-result')).to_contain_text('접근 0회');page.screenshot(path=str(evidence/'result-light.png'),full_page=True);checks.append('confirmed release displays confirmed duration')
  page.locator('#next-session').click();expect(page.locator('#start-focus')).to_be_enabled();page.evaluate('mock.fail=true');page.locator('#preferences summary').click();page.locator('#refresh-focus').click();expect(page.locator('#start-focus')).to_be_disabled();expect(page.locator('#focus-countdown')).to_be_hidden();checks.append('failed refresh prevents start / stale progress')
  page.evaluate("mock.fail=false;mock.state={session_id:'bad',status:'RUNNING'}");page.locator('#refresh-focus').click();expect(page.locator('#focus-title')).to_have_text('실제 상태를 확인해주세요');expect(page.locator('#focus-countdown')).to_be_hidden();checks.append('malformed running response rejected')
  page.evaluate("mock.state={session_id:'uncertain',status:'UNKNOWN',snapshot:{sites:mock.items}}");page.locator('#refresh-focus').click();expect(page.locator('#request-end')).to_have_text('차단 해제 다시 확인');expect(page.locator('#start-focus')).to_be_disabled();expect(page.locator('#focus-countdown')).to_be_hidden();checks.append('unconfirmed recovery offers release retry without running')
  page.evaluate("mock.access={session_id:'uncertain',items:[],total_access:0,repeat_access:0,quarantined_count:2,record_status:'REVIEW_REQUIRED'}");page.locator('#guest-focus-controls [data-page=access]').click();page.locator('#refresh-access').click();expect(page.locator('#access-result')).to_contain_text('2건의 계약 오류');expect(page.locator('#access-result')).to_contain_text('원본을 보존');expect(page.locator('#access-list')).not_to_contain_text('저장된 접근 기록이 없습니다');checks.append('quarantined original events are visible as contract errors, not empty success')
  page.evaluate('mock.state=null');page.locator('#access-page [data-page=focus]').click();page.locator('#refresh-focus').click();expect(page.locator('#start-focus')).to_be_enabled();page.locator('#focus-page .account-button').click();expect(page.locator('#member-status')).to_contain_text('Web에서 로그인');expect(page.locator('#start-focus')).to_be_disabled();expect(page.locator('#member-callback')).to_have_value('chrome-extension://test/popup/popup.html');checks.append('link pending blocks guest execution and exposes only public callback')
  page.evaluate('mock.approve=true');page.locator('#member-check').click();expect(page.locator('#member-status')).to_contain_text('회원 연결 확인 완료');expect(page.locator('#member-execution-panel')).to_be_visible();expect(page.locator('#member-execution-status')).to_contain_text('미확인');expect(page.locator('#start-focus')).to_be_disabled();checks.append('confirmed link queries separate execution status; malformed response never implies RUNNING')
  page.evaluate("mock.memberExecution={status:'RUNNING',session_id:'member-session'}");page.locator('#member-execution-check').click();expect(page.locator('#member-execution-status')).to_contain_text('정책 적용 확인 완료');expect(page.locator('#member-execution-end')).to_be_visible();checks.append('member execution renders coordinator confirmation independently from guest state')
  before=page.evaluate("mock.calls.filter(c=>c.type==='DEV_MEMBER_EXECUTION_END').length");page.once('dialog',lambda d:d.dismiss());page.locator('#member-execution-end').click();assert page.evaluate("mock.calls.filter(c=>c.type==='DEV_MEMBER_EXECUTION_END').length")==before;checks.append('cancel member end sends no command')
  page.once('dialog',lambda d:d.accept());page.locator('#member-execution-end').click();expect(page.locator('#member-execution-status')).to_contain_text('해제 확인 완료');expect(page.locator('#member-execution-end')).to_be_hidden();checks.append('confirmed member release hides end control')
  page.evaluate("mock.auth={...mock.auth,phase:'AUTH_RECOVERY_REQUIRED',owner_user_id:'1',executor_id:'member-executor'};mock.memberExecution={status:'UNCONFIRMED',session_id:'member-session'}");page.locator('#member-check').click();expect(page.locator('#member-execution-panel')).to_be_visible();expect(page.locator('#member-execution-end')).to_be_visible();expect(page.locator('#start-focus')).to_be_disabled();checks.append('auth recovery preserves member cleanup controls without enabling new guest execution')
  page.evaluate("mock.delivery={total:6,retry_after_at:0,next_retry_at:null,counts:{QUEUED:2,IN_FLIGHT:0,RESPONSE_UNCONFIRMED:1,PENDING_DEPENDENCY:0,AUTH_REQUIRED:0,REJECTED:1,ACKED:2,LOCAL_REVIEW_REQUIRED:0}}")
  page.locator('#member-delivery-check').click();expect(page.locator('#member-delivery-status')).to_contain_text('확인했습니다');expect(page.locator('#member-delivery-counts')).to_contain_text('전송 거절');expect(page.locator('#member-delivery-counts dd').nth(5)).to_have_text('1건');checks.append('delivery counts distinguish rejected, uncertain and received records')
  page.locator('#member-delivery-recheck').click();expect(page.locator('#member-delivery-status')).to_contain_text('확인했습니다');assert page.evaluate("mock.calls.some(m=>m.type==='MEMBER_DELIVERY_RECHECK')");checks.append('explicit recheck uses delivery transport')
  page.evaluate('mock.delivery.counts.LOCAL_REVIEW_REQUIRED=1;mock.delivery.total=7');page.locator('#member-delivery-check').click();expect(page.locator('#member-delivery-status')).to_contain_text('문제가 있는 원문은 보존');expect(page.locator('#member-delivery-counts dd').nth(7)).to_have_text('1건');checks.append('local review is distinct from server rejection and success')
  page.evaluate('mock.delivery.retry_after_at=Date.now()+60000;mock.delivery.next_retry_at=mock.delivery.retry_after_at');page.locator('#member-delivery-check').click();expect(page.locator('#member-delivery-wait')).to_contain_text('서버 요청에 따라');expect(page.locator('#member-delivery-recheck')).to_be_disabled();expect(page.locator('#member-delivery-check')).to_be_enabled();checks.append('server cooldown explains wait and keeps local query available')
  page.evaluate('mock.delivery.retry_after_at=0;mock.delivery.next_retry_at=Date.now()-1000');page.locator('#member-delivery-check').click();expect(page.locator('#member-delivery-recheck')).to_be_enabled();expect(page.locator('#member-delivery-wait')).to_contain_text('재확인 가능한 시간');checks.append('elapsed cooldown offers recheck without claiming received or sending automatically')
  page.evaluate('mock.deliveryStorageFail=true');page.locator('#member-delivery-recheck').click();expect(page.locator('#member-delivery-status')).to_contain_text('로컬 저장소');expect(page.locator('#member-delivery-status')).to_contain_text('초기화하지 말고');expect(page.locator('#member-delivery-recheck')).to_be_enabled();checks.append('storage error offers nondestructive recovery and never reports zero success')
  page.evaluate('mock.deliveryStorageFail=false');page.locator('#member-delivery-recheck').click();expect(page.locator('#member-delivery-status')).to_contain_text('문제가 있는 원문은 보존');expect(page.locator('#member-delivery-status')).not_to_contain_text('로컬 저장소');checks.append('successful recheck replaces storage failure notice with actual saved record status')
  page.evaluate('mock.deliveryFail=true');page.locator('#member-delivery-check').click();expect(page.locator('#member-delivery-status')).to_contain_text('미확인');expect(page.locator('#member-delivery-counts dd').nth(5)).to_have_text('1건');checks.append('failed query preserves previous values with uncertainty notice')
  page.evaluate("window.dispatchEvent(new CustomEvent('focurve-member-state',{detail:{linked:false}}))");expect(page.locator('#member-delivery-panel')).to_be_hidden();assert page.locator('#member-delivery-counts').inner_text()=='';checks.append('unlink clears account delivery counts')
  page.evaluate("mock.auth={...mock.auth,phase:'LINKED',guest_start_allowed:false,web_origin:'http://127.0.0.1:5173'}");page.locator('#member-check').click();expect(page.locator('#member-focus-guide')).to_be_visible();expect(page.locator('#guest-focus-controls')).to_be_hidden();expect(page.locator('#member-web-link')).to_have_attribute('href','http://127.0.0.1:5173/');expect(page.locator('#start-focus')).to_be_disabled();checks.append('linked member sees Web guide and no guest start form')
  page.locator('#member-focus-guide [data-page=access]').click();expect(page.locator('#page-subtitle')).to_contain_text('보존된 비회원');page.locator('#access-page [data-page=focus]').click();expect(page.locator('#page-subtitle')).to_contain_text('회원 연결됨');checks.append('preserved guest records remain accessible with explicit owner labels')
  page.locator('#member-focus-check').click();expect(page.locator('#preferences')).to_have_attribute('open','');expect(page.locator('#member-execution-panel')).to_be_visible();checks.append('member guide opens actual execution check without creating a session')
  page.evaluate("mock.auth.web_origin='javascript:alert(1)'");page.locator('#member-check').click();assert page.locator('#member-web-link').get_attribute('href') is None;expect(page.locator('#member-web-link')).to_have_attribute('aria-disabled','true');checks.append('untrusted Web URL is never made navigable')
  page.evaluate("mock.approve=false;mock.auth={...mock.auth,phase:'AUTH_RECOVERY_REQUIRED',web_origin:'http://127.0.0.1:5173'}");page.locator('#member-check').click();expect(page.locator('#member-focus-title')).to_contain_text('연결 확인');expect(page.locator('#member-execution-end')).to_be_visible();checks.append('auth recovery keeps member cleanup available while explaining connection state')
  page.evaluate("mock.state={session_id:'guest-cleanup',status:'UNKNOWN',snapshot:{sites:mock.items}}");page.locator('#refresh-focus').click();expect(page.locator('#guest-focus-controls')).to_be_visible();expect(page.locator('#request-end')).to_have_text('차단 해제 다시 확인');checks.append('existing guest cleanup is not hidden by member guide')
  page.evaluate("mock.state=null;mock.auth={...mock.auth,phase:'UNREGISTERED',owner_user_id:null,executor_id:null,guest_start_allowed:true}");page.locator('#refresh-focus').click();page.locator('#member-check').click();expect(page.locator('#member-focus-guide')).to_be_hidden();expect(page.locator('#guest-focus-controls')).to_be_visible();expect(page.locator('#start-focus')).to_be_enabled();expect(page.locator('#page-subtitle')).to_contain_text('비회원');assert page.locator('#member-web-link').get_attribute('href') is None;checks.append('unlink restores guest form and removes previous Web link')
  page.evaluate("mock.auth={...mock.auth,phase:'LINKED',owner_user_id:'1',executor_id:'member-executor',guest_start_allowed:false};mock.memberExecution={status:'RECOVERY_REQUIRED',session_id:'member-session',access_error:'ACCESS_STORAGE_UNCONFIRMED',capture_release_confirmed:true}");page.locator('#member-check').click();expect(page.locator('#member-execution-status')).to_contain_text('수집 중단·차단 해제 확인');expect(page.locator('#member-execution-end')).to_be_visible();checks.append('capture storage fault explains stopped collection and verified release while offering Server END')
  page.evaluate('mock.memberExecution.capture_release_confirmed=false');page.locator('#member-execution-check').click();expect(page.locator('#member-execution-status')).to_contain_text('차단 해제 확인이 필요');expect(page.locator('#member-execution-status')).not_to_contain_text('수집 중단·차단 해제 확인.');checks.append('failed capture cleanup never displays release confirmation')
  page.evaluate("mock.memberExecution={status:'RELEASED',session_id:'member-session',access_error:'ACCESS_STORAGE_UNCONFIRMED',capture_release_confirmed:true}");page.locator('#member-execution-check').click();expect(page.locator('#member-execution-status')).to_contain_text('일부 기록이 누락');expect(page.locator('#member-execution-status')).not_to_contain_text('종료를 눌러');expect(page.locator('#member-execution-end')).to_be_hidden();checks.append('confirmed Server END keeps partial-record warning without requesting another END')
  assert not errors,errors
  browser.close()
 print(json.dumps({'kind':'product HTML + mocked Chrome API in Chromium','passed':len(checks),'checks':checks},ensure_ascii=False,indent=2))
finally:server.shutdown();server.server_close()
