import { useEffect, useState } from "react";
import { request } from "./api";
import { selectSitePolicy } from "./sitePolicy";
import { allPages, clockTime, dateTime, DateFields, Kpi, label, resultClass, resultLabel, seoulDay, SiteMark, targetName, useWork, type Access, type Page, type Session } from "./FocusShared";

export default function BehaviorRecords({initialHost,initialRange,initialSession="",settings}:{initialHost:string;initialRange:{from:string;to:string};initialSession?:string;settings:()=>void}) {
  const work=useWork();const [items,setItems]=useState<Access[]>([]),[cursor,setCursor]=useState<string|null>(null),[loaded,setLoaded]=useState(false);
  const [from,setFrom]=useState(initialRange.from),[to,setTo]=useState(initialRange.to),[host,setHost]=useState(initialHost),[sessionId,setSessionId]=useState(initialSession),[eventType,setEventType]=useState("");
  const [repeat,setRepeat]=useState(false),[sessions,setSessions]=useState<Session[]>([]),[detail,setDetail]=useState<Access|null>(null),[applied,setApplied]=useState("");
  const [quality,setQuality]=useState<string>(""),[dateOpen,setDateOpen]=useState(false);
  const queryKey=JSON.stringify({from,to,host,sessionId,eventType}); const dirty=loaded&&queryKey!==applied;
  async function load(next:string|null=null){const params=new URLSearchParams({...(from?{from_date:from}:{}),...(to?{to_date:to}:{}),...(host?{host}:{}),...(sessionId?{session_id:sessionId}:{}),...(eventType?{event_type:eventType}:{}),...(next?{cursor:next}:{})});const page=await request<Page<Access>>("/access-events?"+params);const stats=await request<{quality:string}>("/statistics/summary?"+new URLSearchParams({...(from?{from_date:from}:{}),...(to?{to_date:to}:{})}));if(!next)setSessions(await allPages<Session>("/sessions?"+new URLSearchParams({...(from?{from_date:from}:{}),...(to?{to_date:to}:{})})));setItems(old=>next?[...old,...page.items]:page.items);setCursor(page.next_cursor);setQuality(stats.quality);setApplied(queryKey);setLoaded(true);if(!next)setDetail(null);}
  useEffect(()=>{void work.run(()=>load());},[]);
  const visible=repeat?items.filter(i=>i.is_repeat):items;
  const counts=[items.length,items.filter(i=>i.event_type==="BLOCKED_SITE_ACCESS").length,items.filter(i=>i.event_type==="RECORDED_ACCESS").length,items.filter(i=>i.event_type==="BLOCKED_FEATURE_ACCESS").length];
  if(detail)return <RecordDetail event={detail} back={()=>{setDetail(null);work.setError("");}} settings={settings}/>;
  return <section className="page behavior-records"><header className="focus-heading"><h3>행동 기록</h3><p>어떤 대상에 접근했는지, 차단되었는지, 반복했는지 확인하세요.</p></header>
    <form className="record-filters" onSubmit={e=>{e.preventDefault();void work.run(()=>load());}}>
      <div className="filter-line"><button type="button" aria-expanded={dateOpen} onClick={()=>setDateOpen(!dateOpen)}>{from||to?`${from||"최근 7일"} – ${to||"오늘"}`:"최근 7일 · 기간 선택"}</button><label className="sr-label">세션<select aria-label="세션" value={sessionId} onChange={e=>setSessionId(e.target.value)}><option value="">세션: 전체</option>{sessions.map(s=><option key={s.session_id} value={s.session_id}>{dateTime(s.started_at)} · {label(s.execution_status)}</option>)}{sessionId&&!sessions.some(s=>s.session_id===sessionId)&&<option value={sessionId}>직접 지정한 세션</option>}</select></label><label className="sr-label">접근 유형<select aria-label="접근 유형" value={eventType} onChange={e=>setEventType(e.target.value)}><option value="">행동 유형: 전체</option><option value="BLOCKED_SITE_ACCESS">사이트 차단</option><option value="RECORDED_ACCESS">허용하고 기록</option><option value="BLOCKED_FEATURE_ACCESS">내부 기능 제한</option></select></label><label className="repeat-check"><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/>반복 접근만</label></div>
      {dateOpen&&<div className="date-popover"><DateFields from={from} to={to} onFrom={setFrom} onTo={setTo}/><button type="button" onClick={()=>{const day=seoulDay();setFrom(day);setTo(day);}}>오늘</button><button type="button" onClick={()=>{setFrom("");setTo("");}}>최근 7일</button></div>}
      <div className="search-line"><label>대상 도메인<input value={host} placeholder="사이트 도메인 검색 · 예: youtube.com" onChange={e=>setHost(e.target.value)}/></label><button className="primary" disabled={work.busy}>조회</button></div>
      <details className="filter-advanced"><summary>세션 ID로 직접 조회</summary><label>세션 ID<input value={sessionId} onChange={e=>setSessionId(e.target.value)}/></label></details>
    </form>
    {dirty&&<p role="status">필터가 변경되었습니다. 조회를 눌러 새 조건을 적용하세요. 아래는 이전 조회 결과입니다.</p>}
    {work.busy&&<p role="status">기록을 확인하고 있습니다. 이전 결과와 입력을 유지합니다.</p>}{work.error&&<><p role="alert">{work.error}</p>{loaded&&<p>조회에 실패해 마지막 성공 결과를 유지합니다.</p>}</>}
    <div className="focus-kpis four">{["전체 접근","사이트 차단","허용하고 기록","내부 기능 제한"].map((title,i)=><Kpi key={title} title={title} value={!loaded?"—":`${counts[i]}회`} hint={["불러온 기록 · 세 유형의 합계","전체 차단 처리","접근을 허용하고 기록","YouTube Shorts"][i]}/>)}</div>
    <section className="focus-card access-list"><h4>접근 목록</h4><p className="muted">불러온 {items.length}건 중 {visible.length}건 표시{cursor?" · 이전 기록 더 있음":""} · 한국 시간{repeat?" · 불러온 기록에서 반복 접근만 표시":""}</p><div className="table-scroll"><table className="access-table"><caption className="sr-only">접근 목록</caption><colgroup><col style={{width:"14%"}}/><col style={{width:"38%"}}/><col style={{width:"22%"}}/><col style={{width:"26%"}}/></colgroup><thead><tr><th>시간</th><th>접근 대상</th><th>적용된 정책</th><th>접근 상태</th></tr></thead><tbody>{visible.map(item=><tr key={item.event_id} tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void work.run(async()=>setDetail(await request<Access>("/access-events/"+item.event_id)));}}} onClick={()=>{void work.run(async()=>setDetail(await request<Access>("/access-events/"+item.event_id)));}}><td><time title={dateTime(item.occurred_at)}>{clockTime(item.occurred_at)}</time><small>{seoulDay(new Date(item.occurred_at))}</small></td><td><button className="record-target row-link" aria-label={`${targetName(item)} ${clockTime(item.occurred_at)} 상세`}><SiteMark host={item.target_host}/><span>{targetName(item)}{item.feature_code&&<small>{item.target_host}</small>}</span></button></td><td><span className={`policy-badge ${resultClass(item)}`}>{resultLabel(item)}</span></td><td><span className={item.is_repeat?"repeat-state":"first-state"}>{item.is_repeat?`반복 접근 · ${item.target_access_index}번째`:"첫 접근"}</span>{item.quality!=="CONFIRMED"&&<small>{label(item.quality)}</small>}</td></tr>)}</tbody></table></div>
      {loaded&&!visible.length&&<div className="empty-state"><h4>조회된 접근 기록이 없습니다.</h4><p>{repeat?"불러온 기록에 반복 접근이 없습니다. 이전 기록이나 다른 조건을 확인하세요.":"기간과 검색 조건을 확인하세요. 미수집 상태는 접근 없음과 다릅니다."}</p></div>}
      {cursor&&!dirty&&<button className="load-more" disabled={work.busy} onClick={()=>{void work.run(()=>load(cursor));}}>이전 기록 더 보기</button>}
    </section>
    <p className="collection-status">선택 기간 전체 수집 상태: {label(quality)}. {quality==="PARTIAL"?"미수집·전송 대기 구간이 있어 0건을 접근 없음으로 확정할 수 없습니다.":quality==="NO_DATA"?"확인된 수집 자료가 없습니다. 확장 프로그램 연결·수집 상태를 확인하세요.":"늦게 도착한 기록은 실제 발생 시각에 반영됩니다."}</p>

  </section>;
}
function RecordDetail({event,back,settings}:{event:Access;back:()=>void;settings:()=>void}) {
  const work=useWork();const [related,setRelated]=useState<Access[]>([]),[session,setSession]=useState<Session|null>(null),[loaded,setLoaded]=useState(false);
  async function load(){const s=await request<Session>("/sessions/"+event.session_id);const rows=await allPages<Access>("/access-events?"+new URLSearchParams({session_id:event.session_id,host:event.target_host,from_date:s.started_at?seoulDay(new Date(s.started_at)):seoulDay(new Date(event.occurred_at)),to_date:s.ended_at?seoulDay(new Date(s.ended_at)):seoulDay()}));setSession(s);setRelated(rows.filter(x=>x.target_key===event.target_key).sort((a,b)=>a.target_access_index-b.target_access_index));setLoaded(true);}
  useEffect(()=>{window.scrollTo(0,0);void work.run(load);},[event.event_id]);
  const site=selectSitePolicy(event.policy?.sites ?? [],event.target_host);
  return <section className="page record-detail"><header className="focus-heading"><h3>행동 기록 상세</h3><p>선택한 접근의 상세 내용과 당시 적용된 정책을 확인하세요.</p></header><button className="detail-back" onClick={back}>기록 목록으로</button>
    <div className="record-detail-columns"><section className="focus-card detail-main"><SiteMark host={event.target_host}/><h4>{targetName(event)} {event.event_type==="RECORDED_ACCESS"?"접근을 허용하고 기록했습니다":"접근이 제한되었습니다"}</h4><p className="muted">{dateTime(event.occurred_at)} · Asia/Seoul</p><dl className="detail-fields">{[["대상",event.target_host],["행동 유형",resultLabel(event)],["이 대상의 접근 순번",`${event.target_access_index}번째 접근`],["반복 여부",event.is_repeat?"반복 접근":"첫 접근"],["관련 세션",session?`${clockTime(session.started_at)}–${clockTime(session.ended_at)}`:"확인 중"],["확인 상태",label(event.quality)]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p className="muted">같은 세션의 같은 대상에서 첫 유효 접근 이후는 반복 접근입니다. 반복 횟수는 전체 접근에 포함되며 별도로 더하지 않습니다.</p></section>
    <section className="focus-card detail-policy"><h4>발생 당시 적용 정책</h4><p className="muted">현재 사이트 설정과 다를 수 있습니다.</p>{site?<><p>적용 호스트: {site.canonical_host}<br/>분류: {label(site.purpose)}<br/>관리 방식: {label(site.access_policy)}<br/>범위: {site.include_subdomains?"하위 도메인 포함":"해당 도메인만"}<br/>내부 기능 제한: {site.access_policy==="BLOCK"?"전체 차단 우선":site.feature_policies?.some(f=>f.enabled)?"YouTube Shorts 제한":"설정 없음"}</p></>:<p>당시 스냅샷에서 일치하는 사이트 정책을 확인하지 못했습니다.</p>}<button className="primary" onClick={settings}>다음 세션 설정 수정</button></section></div>
    <section className="focus-card detail-timeline"><h4>같은 세션의 이 대상 접근</h4>{related.map(item=><div className="timeline-row" key={item.event_id}><time>{dateTime(item.occurred_at)}</time><span>{item.is_repeat?`${item.target_access_index}번째 · 반복`:"첫 접근"}</span><span>{resultLabel(item)}</span></div>)}{!loaded&&!work.error&&<p role="status">관련 기록을 확인하고 있습니다.</p>}{loaded&&!related.length&&<p>같은 대상의 추가 기록을 찾지 못했습니다.</p>}{work.error&&<><p role="alert">{work.error}</p><button onClick={()=>{void work.run(load);}}>관련 기록 다시 확인</button></>}</section>
  </section>;
}
