import { useEffect, useState } from "react";
import { request, message } from "./api";
const asset = (name: string) => "/assets/figma/" + name;
export function Brand() { return <div className="brand"><span className="brand-mark">FC</span><span><strong>FOCURVE</strong><small>집중 행동 관리</small></span></div>; }
export function ForestPanel({ auth = false }: { auth?: boolean }) { return <aside className={auth ? "auth-forest" : "sidebar-forest"} aria-label="FOCURVE 브랜드">
  <img className={auth ? "auth-forest-image auth-forest-light" : "forest-light"} src={asset(auth ? "auth-imgBrandForestImage.png" : "light-imgBrandForestSidebar.png")} alt="" />
  <img className={auth ? "auth-forest-image auth-forest-dark" : "forest-dark"} src={asset("dark-imgBrandForestSidebar.png")} alt="" />
  <div className="forest-copy"><small>FOCUS, YOUR WAY</small>{auth ? <><span className="brand-mark large">FC</span><h2>더 나은 집중을 위한 시작</h2><p>집중에 필요한 사이트는 남기고,<br/>방해되는 접근은 직접 관리하세요.<br/>기록을 살펴보며 다음 집중을 준비해요.</p><p className="muted">확장 프로그램에서 집중을 시작하고,<br/>웹에서 설정과 기록을 자세히 확인하세요.</p></> : <strong>작은 집중이<br/>더 나은 내일을<br/>만듭니다.</strong>}</div>
</aside>; }
const menu = [["dashboard","집중 현황","대시보드","Dashboard"],["sites","사이트 관리","사이트 관리","Globe"],["sessions","집중 세션","집중 세션","Target"],["logs","행동 기록","행동 기록","File"],["statistics","통계","통계","Chart"],["account","계정·연결","설정","Settings"]];
export function Sidebar({tab,onSelect}:{tab:string;onSelect:(tab:string)=>void}) {
 const [connection,setConnection]=useState<string>("연결 상태 확인 중");
 useEffect(()=>{ let disposed=false; const refresh=()=>{request<unknown[]>("/extension-installations").then(rows=>{if(!disposed)setConnection(rows.length ? "회원 연결된 설치 "+rows.length+"개" : "확장 프로그램 미연결");}).catch(e=>{if(!disposed)setConnection(message(e));});}; refresh();window.addEventListener("focurve:connection-changed",refresh);return()=>{disposed=true;window.removeEventListener("focurve:connection-changed",refresh);}; },[tab]);
 return <aside className="sidebar"><Brand/><nav aria-label="회원 메뉴"><small>워크스페이스</small>{menu.map(([id,label,visible,icon])=><button key={id} type="button" aria-label={label} aria-pressed={tab===id} onClick={()=>onSelect(id)}><span className="nav-icon"><img className="forest-light" src={asset(tab===id ? (icon==="Settings" ? "light-imgDashIconSettings.svg" : "active-imgDashIcon"+icon+".svg") : (icon==="Settings" ? "normal-imgDashIconSettings.svg" : "light-imgDashIcon"+icon+".svg"))} alt=""/><img className="forest-dark" src={asset(tab===id ? (icon==="Settings" ? "light-imgDashIconSettings.svg" : "active-imgDashIcon"+icon+".svg") : "dark-imgDashIcon"+icon+".svg")} alt=""/></span>{visible}</button>)}</nav><ForestPanel/><div className="connection"><img src={asset("light-imgIconPlug.svg")} alt=""/><span>{connection}<small>실제 적용 상태는 집중 세션에서 확인</small><button type="button" onClick={()=>onSelect("sessions")}>연결 안내·상태 확인</button></span></div></aside>;
}
export function WorkspaceHeader({name,tab}:{name:string;tab:string}){ return <header className="workspace-header"><span>워크스페이스 / {menu.find(m=>m[0]===tab)?.[2]??"대시보드"}</span><span>{new Intl.DateTimeFormat("ko-KR",{timeZone:"Asia/Seoul",dateStyle:"long"}).format(new Date())}</span><span className="profile"><i>{name.slice(0,1)}</i>{name}</span></header>; }
export function MailHelp({reset=false}:{reset?:boolean;environment?:{DEV?:boolean;VITE_MAIL_MODE?:string;VITE_DEV_MAILBOX_URL?:string}}){return <div className="mail-help"><p>{reset ? "가입한 이메일이라면 재설정 메일의 링크를 열어 새 비밀번호를 저장하세요. 링크는 30분 동안 한 번만 사용할 수 있습니다." : "이메일의 인증 링크를 열어 인증을 완료한 다음 로그인하세요. 메일이 없다면 인증 메일 재발송을 요청할 수 있습니다."}</p></div>;}
